using Imhotep.Planning.Models;
using Imhotep.State.Abstractions;
using Imhotep.State.Models;
using Microsoft.Extensions.Logging;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Imhotep.State.Services;

/// <summary>
/// ISL v2.2: Manages the durable state and memory records of the platform, ensuring safe 
/// continuity and recovery across long-running autonomous execution cycles.
/// </summary>
public interface IStateManager
{
   // --- 1. TRANSACTIONAL STATE CONTROL (ISL v2.2 Sec 26.0) ---

   /// <summary>
   /// Commits a formal state transition transaction across multiple state categories atomically.
   /// Replaces raw updates to ensure cross-state consistency invariants are maintained [1].
   /// </summary>
   Task CommitStateTransactionAsync(StateTransitionTransaction transaction, CancellationToken cancellationToken = default);

   /// <summary>
   /// Retrieves the current operational state for a specific object and category.
   /// </summary>
   Task<PlatformStateRecord?> GetCurrentStateAsync(string objectId, string stateCategory, CancellationToken cancellationToken = default);

   // --- 2. DURABLE MEMORY & EVENT LOGGING (ISL v2.2 Sec 9.0) ---

   /// <summary>
   /// Records an immutable state transition or lifecycle event into the durable event log.
   /// State events form the platform's chronological memory [2].
   /// </summary>
   Task RecordStateEventAsync(StateEventRecord record, CancellationToken cancellationToken = default);

   /// <summary>
   /// Retrieves the chronological memory history of tasks, agents, or artifacts to support 
   /// traceability, audit, and recovery.
   /// </summary>
   Task<IReadOnlyList<StateEventRecord>> GetMemoryHistoryAsync(string correlationId, CancellationToken cancellationToken = default);

   // --- 3. SNAPSHOTS & DETERMINISTIC RECOVERY (ISL v2.2 Sec 28.0 & 29.0) ---

   /// <summary>
   /// Creates a point-in-time capture of state and graph structures for safe recovery [3].
   /// </summary>
   Task<string> CreateSnapshotAsync(StateSnapshotRequest request, CancellationToken cancellationToken = default);

   /// <summary>
   /// Deterministically reconstructs platform state from durable records and snapshots after an interruption.
   /// The platform MUST NOT resume execution until recovery validation completes [4].
   /// </summary>
   Task<RecoveryOutcomeRecord> InitiateRecoveryAsync(string snapshotId, CancellationToken cancellationToken = default);

   // --- 4. CONNECTION CONTEXTS (ISL v1.5 Sec 19.7) ---

   /// <summary>
   /// Persists the Boundary Continuation Record, preserving the explicit state and artifacts 
   /// generated by a boundary for downstream Connection Contexts [5, 6].
   /// </summary>
   Task CommitBoundaryContinuationAsync(BoundaryContinuationRecord record, CancellationToken cancellationToken = default);

   /// <summary>
   /// Retrieves a previously committed continuation record to satisfy Boundary Entry Criteria.
   /// </summary>
   Task<BoundaryContinuationRecord?> GetBoundaryContinuationAsync(string continuationRecordId, CancellationToken cancellationToken = default);

   // --- 5. EXECUTION & TASK STATE (ISL v2.2 Sec 14.0 & 15.0) ---

   /// <summary>
   /// Retrieves the current execution graph state for a given plan, allowing the runtime 
   /// to safely resume execution after an interruption.
   /// </summary>
   Task<ConstructionTaskGraph> GetExecutionGraphAsync(string planId, CancellationToken cancellationToken = default);

   /// <summary>
   /// Durably updates the state of a specific task within the execution graph.
   /// Behind the scenes, this should invoke CommitStateTransactionAsync to ensure consistency.
   /// </summary>
   Task UpdateTaskStateAsync(string planId, ConstructionTask task, CancellationToken cancellationToken = default);

   // --- 6. REPAIR STATE (ISL v2.2 Sec 18.0) ---

   /// <summary>
   /// Retrieves the durable repair history for a specific task to mathematically enforce 
   /// the repair termination limits defined in ISL v1.2 Sec 15.2.
   /// </summary>
   Task<IReadOnlyList<RepairRecord>> GetRepairRecordsForTaskAsync(string taskId, CancellationToken cancellationToken = default);

   /// <summary>
   /// Persists a formal Repair Record to durably track automated repair attempts [ISL v1.2 Sec 15.3].
   /// This ensures the Repair Analyst agent knows exactly what prior fixes failed.
   /// </summary>
   Task SaveRepairRecordAsync(RepairRecord record, CancellationToken cancellationToken = default);
}

/// <summary>
/// ISL v2.2: Manages the durable state and memory records of the platform, ensuring safe 
/// continuity and recovery across long-running autonomous execution cycles.
/// </summary>
public class StateManager : IStateManager
{
   private readonly ILogger<StateManager> _logger;

   // In-memory persistent stores for the MACS POC
   private readonly ConcurrentDictionary<string, PlatformStateRecord> _activeStateStore = new();
   private readonly ConcurrentBag<StateEventRecord> _eventLog = new();
   private readonly ConcurrentDictionary<string, BoundaryContinuationRecord> _continuationStore = new();

   private readonly ConcurrentDictionary<string, ConstructionTaskGraph> _pocExecutionGraphStore = new();

   // Generic, reusable stores injected via DI
   private readonly ILogicalStateStore<ConstructionTaskGraph> _executionGraphStore;
   private readonly ILogicalStateStore<RepairRecord> _repairRecordStore;

   public StateManager(
       ILogicalStateStore<ConstructionTaskGraph> executionGraphStore,
       ILogicalStateStore<RepairRecord> repairRecordStore,
       ILogger<StateManager> logger)
   {
      _executionGraphStore = executionGraphStore;
      _repairRecordStore = repairRecordStore;
      _logger = logger;
   }

   // --- 1. TRANSACTIONAL STATE CONTROL (ISL v2.2 Sec 26.0) ---

   public Task CommitStateTransactionAsync(StateTransitionTransaction transaction, CancellationToken cancellationToken = default)
   {
      cancellationToken.ThrowIfCancellationRequested();

      _logger.LogInformation("Committing State Transaction {TransactionId} of type {Type}. Status: {Status}",
          transaction.TransactionId, transaction.TransactionType, transaction.Status);

      // ISL v2.2 Sec 26.3: A failed transaction MUST enter a failed or compensating state [6].
      if (transaction.Status is "failed" or "compensating")
      {
         _logger.LogWarning("Transaction {TransactionId} failed. Recovery Action: {Action}",
             transaction.TransactionId, transaction.RecoveryAction);
      }

      return Task.CompletedTask;
   }

   public Task<PlatformStateRecord?> GetCurrentStateAsync(string objectId, string stateCategory, CancellationToken cancellationToken = default)
   {
      cancellationToken.ThrowIfCancellationRequested();

      var compositeKey = $"{objectId}::{stateCategory}";
      _activeStateStore.TryGetValue(compositeKey, out var state);

      return Task.FromResult(state);
   }

   // --- 2. DURABLE MEMORY & EVENT LOGGING (ISL v2.2 Sec 9.0) ---

   public Task RecordStateEventAsync(StateEventRecord record, CancellationToken cancellationToken = default)
   {
      cancellationToken.ThrowIfCancellationRequested();

      _logger.LogDebug("Recording State Event {EventId} [{EventType}] for Object {ObjectId}",
          record.StateEventId, record.EventType, record.ObjectId);

      _eventLog.Add(record);
      return Task.CompletedTask;
   }

   public Task<IReadOnlyList<StateEventRecord>> GetMemoryHistoryAsync(string correlationId, CancellationToken cancellationToken = default)
   {
      cancellationToken.ThrowIfCancellationRequested();

      var history = _eventLog
          .Where(r => r.CorrelationId == correlationId)
          .OrderBy(r => r.EventTime)
          .ThenBy(r => r.EventSequence)
          .ToList();

      return Task.FromResult<IReadOnlyList<StateEventRecord>>(history);
   }

   // --- 3. SNAPSHOTS & DETERMINISTIC RECOVERY (ISL v2.2 Sec 28.0 & 29.0) ---

   public Task<string> CreateSnapshotAsync(StateSnapshotRequest request, CancellationToken cancellationToken = default)
   {
      cancellationToken.ThrowIfCancellationRequested();

      string snapshotId = $"SNAP-{request.SnapshotType}-{Guid.NewGuid().ToString("N")[..8]}";

      _logger.LogInformation("Created persistent {SnapshotType} snapshot {SnapshotId} by {Actor}",
          request.SnapshotType, snapshotId, request.CreatedBy);

      return Task.FromResult(snapshotId);
   }

   public Task<RecoveryOutcomeRecord> InitiateRecoveryAsync(string snapshotId, CancellationToken cancellationToken = default)
   {
      cancellationToken.ThrowIfCancellationRequested();

      _logger.LogWarning("Initiating recovery from snapshot {SnapshotId}. Validating state consistency.", snapshotId);

      // Simulate deterministic reconstruction and consistency validation [7]
      var outcome = new RecoveryOutcomeRecord
      {
         RecoveryEventId = Guid.NewGuid().ToString(),
         RecoveryScope = "full-platform",
         AffectedObjectIds = new List<string>(),
         ConsistencyStatus = "consistent",
         RecoveryOutcome = "resume-safe", // Safe to resume execution [8]
         RecoveredAt = DateTimeOffset.UtcNow
      };

      return Task.FromResult(outcome);
   }

   // --- 4. CONNECTION CONTEXTS (ISL v1.5 Sec 19.7) ---

   public Task CommitBoundaryContinuationAsync(BoundaryContinuationRecord record, CancellationToken cancellationToken = default)
   {
      cancellationToken.ThrowIfCancellationRequested();

      _logger.LogInformation("Persisting Boundary Continuation Record {RecordId} for Boundary {BoundaryId}",
          record.ContinuationRecordId, record.BoundaryId);

      _continuationStore[record.ContinuationRecordId] = record;
      return Task.CompletedTask;
   }

   public Task<BoundaryContinuationRecord?> GetBoundaryContinuationAsync(string continuationRecordId, CancellationToken cancellationToken = default)
   {
      cancellationToken.ThrowIfCancellationRequested();

      _continuationStore.TryGetValue(continuationRecordId, out var record);
      return Task.FromResult(record);
   }

   // --- 5. EXECUTION & TASK STATE (ISL v2.2 Sec 14.0 & 15.0) ---

   /// <summary>
   /// ISL v2.2 Sec 14.0: Execution State.
   /// Retrieves the current execution graph state for a given plan from durable memory,
   /// allowing the runtime to safely resume execution after an interruption.
   /// </summary>
   public Task<ConstructionTaskGraph> GetExecutionGraphAsync(
       string planId,
       CancellationToken cancellationToken = default)
   {
      cancellationToken.ThrowIfCancellationRequested();

      _logger.LogInformation("Retrieving durable Execution Graph state for Plan {PlanId}", planId);

      // 1. In a production system, this would query a persistent database 
      // using the ISL v2.2 Execution State Schema.

      // 2. For the MACS POC, we retrieve it from our simulated durable store
      if (!_pocExecutionGraphStore.TryGetValue(planId, out var taskGraph))
      {
         // ISL v2.2 Sec 33.2: Map to the 'state-record-missing' error class
         _logger.LogError("STATE-RECORD-MISSING: Execution Graph {PlanId} not found in durable memory.", planId);
         throw new KeyNotFoundException($"ISL v2.2 State Violation: Execution Graph {planId} could not be located in durable memory. The platform cannot resume execution.");
      }

      return Task.FromResult(taskGraph);
   }

   /// <summary>
   /// ISL v2.2 Sec 15.0: Task State.
   /// Durably updates the state of a specific task within the execution graph.
   /// In a full enterprise system, this invokes CommitStateTransactionAsync to ensure multi-record consistency.
   /// </summary>
   public Task UpdateTaskStateAsync(
       string planId,
       ConstructionTask task,
       CancellationToken cancellationToken = default)
   {
      cancellationToken.ThrowIfCancellationRequested();

      _logger.LogInformation("Committing state transition for Task {TaskId} to '{Status}' in Plan {PlanId}",
          task.TaskId, task.Status, planId);

      // 1. Retrieve the durable execution graph [ISL v2.2 Sec 14.0]
      if (!_pocExecutionGraphStore.TryGetValue(planId, out var taskGraph))
      {
         _logger.LogError("STATE-RECORD-MISSING: Execution Graph {PlanId} not found in durable memory.", planId);
         throw new KeyNotFoundException($"ISL v2.2 State Violation: Execution Graph {planId} could not be located.");
      }

      // 2. Locate the existing task to verify it exists
      var existingTasks = taskGraph.Tasks.ToList();
      int taskIndex = existingTasks.FindIndex(t => t.TaskId == task.TaskId);

      if (taskIndex == -1)
      {
         _logger.LogError("STATE-RECORD-MISSING: Task {TaskId} not found in Execution Graph {PlanId}.", task.TaskId, planId);
         throw new KeyNotFoundException($"ISL v2.2 State Violation: Task {task.TaskId} could not be found.");
      }

      // 3. Replace the old task with the new immutable task snapshot
      existingTasks[taskIndex] = task;

      // 4. Create an immutable snapshot of the updated graph
      var updatedGraph = taskGraph with { Tasks = existingTasks };

      // 5. Persist the updated graph back to the durable store [ISL v2.2 Sec 5.2]
      _pocExecutionGraphStore[planId] = updatedGraph;

      // 6. ISL v2.2 Sec 9.0: In a fully scaled implementation, you would also emit a State Event here:
      // await RecordStateEventAsync(new StateEventRecord { EventType = "task-state-changed", ... });

      _logger.LogInformation("Successfully committed state transition for Task {TaskId}.", task.TaskId);

      return Task.CompletedTask;
   }

   /// <summary>
   /// ISL v2.2 Sec 18.0: Repair State.
   /// Retrieves the durable repair history for a specific task to mathematically enforce 
   /// the repair termination limits defined in ISL v1.2 Sec 15.2.
   /// </summary>
   public async Task<IReadOnlyList<RepairRecord>> GetRepairRecordsForTaskAsync(
       string taskId,
       CancellationToken cancellationToken = default)
   {
      _logger.LogInformation("Retrieving durable repair records for Task {TaskId}", taskId);

      // Use the generic Find method to retrieve records
      var records = await _repairRecordStore.FindAsync(r => r.TaskId == taskId, cancellationToken);

      // Ensure chronological order [ISL v2.2 Sec 9.0]
      return records.OrderBy(r => r.Iteration).ToList();
   }

   /// <summary>
   /// ISL v2.2 Sec 18.0: Repair State.
   /// Persists a formal Repair Record to durably track automated repair attempts.
   /// </summary>
   public async Task SaveRepairRecordAsync(
       RepairRecord record,
       CancellationToken cancellationToken = default)
   {
      _logger.LogInformation("Persisting Repair Record {RepairId} for Task {TaskId} (Iteration {Iteration})",
          record.RepairId, record.TaskId, record.Iteration);

      // Durably save using the generic upsert operation
      await _repairRecordStore.UpsertAsync(record.RepairId, record, cancellationToken);

      _logger.LogInformation("Successfully saved Repair Record {RepairId}. Task {TaskId} is now officially in-repair.",
          record.RepairId, record.TaskId);
   }

}
